import requests

url = 'http://localhost:3000/rest/admin/application-configuration'
headers = {
    'Authorization':'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MSwidXNlcm5hbWUiOiIiLCJlbWFpbCI6ImFkbWluQGp1aWNlLXNoLm9wIiwicGFzc3dvcmQiOiIwMTkyMDIzYTdiYmQ3MzI1MDUxNmYwNjlkZjE4YjUwMCIsInJvbGUiOiJhZG1pbiIsImRlbHV4ZVRva2VuIjoiIiwibGFzdExvZ2luSXAiOiJ1bmRlZmluZWQiLCJwcm9maWxlSW1hZ2UiOiJhc3NldHMvcHVibGljL2ltYWdlcy91cGxvYWRzL2RlZmF1bHRBZG1pbi5wbmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjMtMDgtMDUgMTQ6NTQ6MjkuNzE0ICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjMtMDgtMDUgMTg6NDQ6MzIuNTAyICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImlhdCI6MTY5MTQ0MTU3N30.h7lJOUwtJyTbAWTvLfEf5r_sarxlay1mxqJad6y_ItmiUmMYnr5sfaF8lHFdhDUhPXfJQ9EUYI4X2vHK0J7eWg8tT-uGe7fnpzhBl6CeyqDTeyCrCKtLQhM_3mijRzHm05lOEFjik9AeAA2qN0UJMRzpxD3Lc--a8dUrYCyIDw0',
    'Cookie':'language=en; welcomebanner_status=dismiss; cookieconsent_status=dismiss; continueCode=POq8XxDzbkeJ7mY61E2joZGm7tMH6C6fb1UB6ALNgpK9BRya5Ww3lQ4VvnMr; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AanVpY2Utc2gub3AiLCJwYXNzd29yZCI6IjAxOTIwMjNhN2JiZDczMjUwNTE2ZjA2OWRmMThiNTAwIiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6InVuZGVmaW5lZCIsInByb2ZpbGVJbWFnZSI6ImFzc2V0cy9wdWJsaWMvaW1hZ2VzL3VwbG9hZHMvZGVmYXVsdEFkbWluLnBuZyIsInRvdHBTZWNyZXQiOiIiLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyMy0wOC0wNVQxNDo1NDoyOS43MTRaIiwidXBkYXRlZEF0IjoiMjAyMy0wOC0wN1QyMDo1NToyNi43NTRaIiwiZGVsZXRlZEF0IjpudWxsfSwiaWF0IjoxNjkxNDQxNzI3fQ.Pcb_7BlDZedJ62jLoJ_r-qrk-EZiguR_P0aqyVfzDBoFDSQVwuuuEBRPKQd5QRpjP4k1pVPMdR5o84Z_k6b6W9REXPp9d-yVqAFEYykCY4TxfgEej3sgzsacdNFUzOPrIM9PQ7_F9A2h8lQvrZhzviv5Xyy55Zol0tGjr1gpwu4'
    }
response = requests.get(url,headers=headers)

print(response.status_code)
print(response.text)
