# Get
$url = 'http://localhost:3000/api/Feedbacks/'
$headers = @{
    'Authorization'='Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MjUsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJub2JvZHk1QG5vYm9keS5jb20iLCJwYXNzd29yZCI6IjZlODU0NDQyY2QyYTk0MGM5ZTk1OTQxZGNlNGFkNTk4Iiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0QWRtaW4ucG5nIiwidG90cFNlY3JldCI6IiIsImlzQWN0aXZlIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIzLTA4LTEyIDEzOjQwOjI0LjYzMiArMDA6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA4LTEyIDEzOjQwOjI0LjYzMiArMDA6MDAiLCJkZWxldGVkQXQiOm51bGx9LCJpYXQiOjE2OTE4Njc3NzB9.cQ2QDqpC3gbhCOJKj-Mvx7EjFLhOnCNAtcUvLi_QBZxgEaU299PxSWvBK-YwT7mY3i-0L7HgK1-aB7dV-pyq4_2yeVDESOr_LmHLJx-yBTnOtUvDuJ9S_b6cjAZLA2FkV2k9kDlNSzUKg1i5mCL2V8JxZhjSP-B1qteB8um7OYg'
}
$feedbackResponse = Invoke-RestMethod -Method Get -Uri $url -Headers $headers
$feedback = $feedbackResponse.data
$feedback


# Delete
$url = 'http://localhost:3000/api/Feedbacks/1'
$headers = @{
    'Authorization'='Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MjUsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJub2JvZHk1QG5vYm9keS5jb20iLCJwYXNzd29yZCI6IjZlODU0NDQyY2QyYTk0MGM5ZTk1OTQxZGNlNGFkNTk4Iiwicm9sZSI6ImFkbWluIiwiZGVsdXhlVG9rZW4iOiIiLCJsYXN0TG9naW5JcCI6IjAuMC4wLjAiLCJwcm9maWxlSW1hZ2UiOiIvYXNzZXRzL3B1YmxpYy9pbWFnZXMvdXBsb2Fkcy9kZWZhdWx0QWRtaW4ucG5nIiwidG90cFNlY3JldCI6IiIsImlzQWN0aXZlIjp0cnVlLCJjcmVhdGVkQXQiOiIyMDIzLTA4LTEyIDEzOjQwOjI0LjYzMiArMDA6MDAiLCJ1cGRhdGVkQXQiOiIyMDIzLTA4LTEyIDEzOjQwOjI0LjYzMiArMDA6MDAiLCJkZWxldGVkQXQiOm51bGx9LCJpYXQiOjE2OTE4Njc3NzB9.cQ2QDqpC3gbhCOJKj-Mvx7EjFLhOnCNAtcUvLi_QBZxgEaU299PxSWvBK-YwT7mY3i-0L7HgK1-aB7dV-pyq4_2yeVDESOr_LmHLJx-yBTnOtUvDuJ9S_b6cjAZLA2FkV2k9kDlNSzUKg1i5mCL2V8JxZhjSP-B1qteB8um7OYg'
}
$feedbackResponse = Invoke-RestMethod -Method Delete -Uri $url -Headers $headers
$feedback = $feedbackResponse.data

# Post feedback as another user
Foreach($email in $emails)
{
    $headers = @{
        'Authorization' = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MjQsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJzb21lYm9keTNAbm9ib2R5LmNvbSIsInBhc3N3b3JkIjoiZjQzZWIzMWExYTFiOTRlYzI4Zjc1Njk4MzY1YmIwOWYiLCJyb2xlIjoiYWRtaW4iLCJkZWx1eGVUb2tlbiI6IiIsImxhc3RMb2dpbklwIjoiMC4wLjAuMCIsInByb2ZpbGVJbWFnZSI6Ii9hc3NldHMvcHVibGljL2ltYWdlcy91cGxvYWRzL2RlZmF1bHRBZG1pbi5wbmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjMtMDgtMjAgMTg6MDc6NTUuMTU3ICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjMtMDgtMjAgMTg6MDc6NTUuMTU3ICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImlhdCI6MTY5MjU1NDg4N30.QeM8WPDRCKxFUwi-a4cbahdyjZ_YmF9CoPF93cYN1185X3nKiFquM2bKJxTo8ZLJn8IjE5a_ZwKF8EBb8-M4eW3eHsFUDmC0j1bwJnDlXQJXW6Hny0LBX9yPAZfqoy3UzHdNeUSjmz5XxbAdBVxhICFye99cFbXJ-OfVD6gt6rQ'
        'Cookie' = 'language=en; welcomebanner_status=dismiss; cookieconsent_status=dismiss; continueCode=qzlEeMamvRr5owgNVW2A4ohLHnilf2XH1qCBWUrv07p4QbZ8BxKL9D3OkP1X; token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MjQsInVzZXJuYW1lIjoiIiwiZW1haWwiOiJzb21lYm9keTNAbm9ib2R5LmNvbSIsInBhc3N3b3JkIjoiZjQzZWIzMWExYTFiOTRlYzI4Zjc1Njk4MzY1YmIwOWYiLCJyb2xlIjoiYWRtaW4iLCJkZWx1eGVUb2tlbiI6IiIsImxhc3RMb2dpbklwIjoiMC4wLjAuMCIsInByb2ZpbGVJbWFnZSI6Ii9hc3NldHMvcHVibGljL2ltYWdlcy91cGxvYWRzL2RlZmF1bHRBZG1pbi5wbmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjMtMDgtMjAgMTg6MDc6NTUuMTU3ICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjMtMDgtMjAgMTg6MDc6NTUuMTU3ICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImlhdCI6MTY5MjU1NDg4N30.QeM8WPDRCKxFUwi-a4cbahdyjZ_YmF9CoPF93cYN1185X3nKiFquM2bKJxTo8ZLJn8IjE5a_ZwKF8EBb8-M4eW3eHsFUDmC0j1bwJnDlXQJXW6Hny0LBX9yPAZfqoy3UzHdNeUSjmz5XxbAdBVxhICFye99cFbXJ-OfVD6gt6rQ'
    }
    $url = 'http://localhost:3000/rest/products/24/reviews'
    $payload = @{
        'author' = $email
        'message' = "$email was here"
    }
    $feedbackSomeoneElseResponse = Invoke-RestMethod -Method Put -Uri $url -Headers $headers -Body $payload
    $feedbackSomeoneElseResponse
}